env:
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  eqeqeq: error
  no-else-return: error
  no-useless-return: error
  no-useless-catch: error
  eol-last: 
    - error
    - always
  curly: error
  no-return-await: error
  camelcase: warn
  dot-notation: error
  no-multi-spaces: warn
  require-await: warn
  keyword-spacing:
    - error
    - before: true
      after: true
  func-call-spacing:
    - error
    - never
  object-curly-spacing:
    - error
    - always
    - arraysInObjects: false
      objectsInObjects: false
  '@typescript-eslint/no-explicit-any': error
  '@typescript-eslint/member-ordering': error
  '@typescript-eslint/no-require-imports': error
  '@typescript-eslint/explicit-function-return-type': error
  '@typescript-eslint/type-annotation-spacing': error
  '@typescript-eslint/typedef':
    - error
    - arrayDestructuring: false
      arrowParameter: true
      memberVariableDeclaration: true
      objectDestructuring: false
      parameter: true
      propertyDeclaration: true
      variableDeclaration: true
      variableDeclarationIgnoreFunction: true
